name: getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  collapsible_sidebar: ^2.0.1+2
  flutter_neumorphic: ^3.2.0
  font_awesome_flutter: ^10.1.0
  syncfusion_flutter_calendar: ^20.1.58
  carousel_slider: ^4.1.1
  google_fonts: 3.0.1
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.5.3+2

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/image/
  uses-material-design: true

